import "server-only";

import { anthropic } from "@ai-sdk/anthropic";
import { generateText } from "ai";
import { Hash, Sparkles, TrendingUp } from "lucide-react";

import { createClient } from "@/lib/supabase/server";
import { isAiAllowedForUser } from "@/lib/ai/guards";
import { getServerT } from "@/lib/i18n-server";
import { cn } from "@/lib/utils";

// "Today's Brain" — server-rendered summary card at the top of the
// dashboard. Three bullets generated by Haiku 4.5 from the last 7
// days of notes, top 3 active tags, and a mini activity sparkline.
//
// Wrapped in a Suspense boundary by the page so the notes grid
// doesn't block on the Haiku call. Falls back gracefully when the
// AI guard blocks (non-allowlisted user) or when there are too few
// notes to summarise.
//
// Latency budget: ~1.5–3 s for the Haiku call + ~50 ms for the
// supabase fetch. The Suspense boundary keeps the rest of the page
// interactive in the meantime.

const SUMMARISER_SYSTEM =
    "You produce a personal weekly brain dump for the user, from the notes they wrote in the last 7 days. Return EXACTLY 3 short bullets in the user's language (detect from the notes). Each bullet starts with '- ', is one short sentence, captures a theme or recurring topic, and never mentions personally-identifying information unless it was already in the notes. Do NOT add a preamble, a header, or anything other than the 3 bullet lines.";

type Note = {
    id: number;
    title: string | null;
    content: string;
    tags: string[] | null;
    created_at: string;
};

async function loadTodayBrain(userId: string) {
    const supabase = await createClient();
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
        .toISOString();
    const fourteenDaysAgo = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)
        .toISOString();

    const { data: recent } = await supabase
        .from("notes")
        .select("id, title, content, tags, created_at")
        .gte("created_at", fourteenDaysAgo)
        .is("archived_at", null)
        .order("created_at", { ascending: true });

    const notes = (recent ?? []) as Note[];
    if (notes.length === 0) {
        return null;
    }

    // Activity sparkline: count of notes per day for the last 14 days
    const sparkline = computeDailyCounts(notes, 14);

    // Last 7 days for summary + tag stats
    const last7 = notes.filter((n) => n.created_at >= sevenDaysAgo);
    if (last7.length === 0) {
        return { bullets: [], topTags: [], sparkline, weekCount: 0 };
    }

    // Top 3 tags from the last 7 days
    const tagCount = new Map<string, number>();
    for (const n of last7) {
        for (const t of n.tags ?? []) {
            tagCount.set(t, (tagCount.get(t) ?? 0) + 1);
        }
    }
    const topTags = Array.from(tagCount.entries())
        .sort((a, b) => b[1] - a[1])
        .slice(0, 3)
        .map(([name, count]) => ({ name, count }));

    let bullets: string[] = [];
    if (isAiAllowedForUser(userId)) {
        try {
            bullets = await summariseWeek(last7);
        } catch {
            // Fail-soft: if Haiku is unavailable or the response is
            // malformed, show the card without bullets rather than
            // breaking the dashboard.
            bullets = [];
        }
    }

    return { bullets, topTags, sparkline, weekCount: last7.length };
}

async function summariseWeek(notes: Note[]): Promise<string[]> {
    const corpus = notes
        .map((n) => {
            const title = n.title?.trim() || `Note ${n.id}`;
            const body = n.content.trim().slice(0, 500);
            return `## ${title}\n${body}`;
        })
        .join("\n\n---\n\n");

    const { text } = await generateText({
        model: anthropic("claude-haiku-4-5"),
        system: SUMMARISER_SYSTEM,
        prompt: `Notes from the last 7 days (${notes.length} total):\n\n${corpus}`,
    });

    return text
        .split("\n")
        .map((line) => line.replace(/^[-*•]\s*/, "").trim())
        .filter((line) => line.length > 0)
        .slice(0, 3);
}

function computeDailyCounts(notes: Note[], days: number): number[] {
    const counts = new Array(days).fill(0) as number[];
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    for (const n of notes) {
        const created = new Date(n.created_at);
        created.setHours(0, 0, 0, 0);
        const diff = Math.floor(
            (today.getTime() - created.getTime()) / (24 * 60 * 60 * 1000),
        );
        const idx = days - 1 - diff;
        if (idx >= 0 && idx < days) counts[idx]! += 1;
    }
    return counts;
}

export async function TodayBrainCard({ userId }: { userId: string }) {
    const data = await loadTodayBrain(userId);
    if (!data) return null;

    const t = await getServerT();
    const max = Math.max(1, ...data.sparkline);

    return (
        <section
            className={cn(
                "relative rounded-xl border border-border/60 bg-gradient-to-br from-primary/[0.04] via-background to-background p-5 backdrop-blur-sm",
                "shadow-[0_1px_2px_rgba(0,0,0,0.04),0_8px_24px_-12px_rgba(231,161,60,0.18)]",
                "animate-in fade-in slide-in-from-top-2 duration-500",
            )}
            data-test="today-brain-card"
        >
            {/* Header */}
            <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                    <div className="rounded-lg bg-primary/10 p-1.5">
                        <Sparkles className="h-3.5 w-3.5 text-primary" />
                    </div>
                    <h2 className="text-sm font-semibold tracking-tight text-foreground">
                        {t.todayBrain.title}
                    </h2>
                    <span className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">
                        {t.todayBrain.lastDays(data.weekCount)}
                    </span>
                </div>
                <Sparkline
                    values={data.sparkline}
                    max={max}
                    label={t.todayBrain.activityAria}
                />
            </div>

            {/* Bullets */}
            {data.bullets.length > 0 ? (
                <ul className="space-y-2 mb-4">
                    {data.bullets.map((b, i) => (
                        <li
                            key={i}
                            className={cn(
                                "flex gap-2.5 text-sm leading-relaxed text-foreground",
                                "animate-in fade-in slide-in-from-left-1",
                            )}
                            style={{ animationDelay: `${i * 90 + 100}ms` }}
                        >
                            <span
                                className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-primary"
                                aria-hidden
                            />
                            <span>{b}</span>
                        </li>
                    ))}
                </ul>
            ) : (
                data.weekCount > 0 && (
                    <p className="mb-4 text-sm text-muted-foreground italic">
                        {t.todayBrain.aiUnavailable(data.weekCount)}
                    </p>
                )
            )}

            {/* Top tags */}
            {data.topTags.length > 0 && (
                <div className="flex items-center gap-2 pt-3 border-t border-border/40">
                    <TrendingUp className="h-3 w-3 text-muted-foreground" />
                    <span className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">
                        {t.todayBrain.topTags}
                    </span>
                    <div className="flex flex-wrap gap-1.5">
                        {data.topTags.map((t) => (
                            <span
                                key={t.name}
                                className="inline-flex items-center gap-1 text-[11px] px-1.5 py-0.5 rounded border border-border/60 bg-muted/40 text-foreground font-mono"
                            >
                                <Hash className="h-2.5 w-2.5 text-muted-foreground" />
                                {t.name}
                                <span className="text-muted-foreground">
                                    {t.count}
                                </span>
                            </span>
                        ))}
                    </div>
                </div>
            )}
        </section>
    );
}

function Sparkline({
    values,
    max,
    label,
}: {
    values: number[];
    max: number;
    label: string;
}) {
    // 14 bars rendered as inline SVG so it sits cleanly in the header
    // row alongside the title. Heights scale to the max value in the
    // window so the visualisation always uses the available space.
    const width = 84;
    const height = 18;
    const gap = 1.5;
    const barW = (width - gap * (values.length - 1)) / values.length;

    return (
        <svg
            width={width}
            height={height}
            viewBox={`0 0 ${width} ${height}`}
            aria-label={label}
            role="img"
            className="text-primary/80"
        >
            {values.map((v, i) => {
                const h = max > 0 ? (v / max) * height : 0;
                const x = i * (barW + gap);
                const y = height - h;
                return (
                    <rect
                        key={i}
                        x={x}
                        y={y}
                        width={barW}
                        height={Math.max(h, 0.8)}
                        rx={0.6}
                        className={cn(
                            v === 0
                                ? "fill-muted-foreground/30"
                                : "fill-current",
                        )}
                    />
                );
            })}
        </svg>
    );
}

export function TodayBrainSkeleton() {
    return (
        <section className="relative rounded-xl border border-border/60 bg-background/50 p-5 animate-pulse">
            <div className="flex items-center gap-2 mb-4">
                <div className="h-7 w-7 rounded-lg bg-muted" />
                <div className="h-3 w-32 bg-muted rounded" />
            </div>
            <div className="space-y-2 mb-4">
                <div className="h-3 w-full bg-muted rounded" />
                <div className="h-3 w-[85%] bg-muted rounded" />
                <div className="h-3 w-[70%] bg-muted rounded" />
            </div>
            <div className="h-4 w-48 bg-muted rounded" />
        </section>
    );
}
